[namespaces]
"xml:base" = "http://prgmon.com/onotology/tutorial"
"xmlns:rdf" = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
"xmlns:rdfs" = "http://www.w3.org/2000/01/rdf-schema#"
"xmlns:ex" = "http://prgmon.com/ontology/tutorial/1#"
"xmlns:owl" = "http://www.w3.org/2002/07/owl#"
"xmlns:xml" = "http://www.w3.org/XML/1998/namespace"
"xmlns:xsd" = "http://www.w3.org/2001/XMLSchema#"

[status]
violation_score = 0.0

[[subClassOf]]
subject = "ex:Cat"
parent = "ex:Animal"
priority = 1.0
violation = 0
depth = 0
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:NeuroRobot"
parent = "ex:Animal"
priority = 1.0
violation = 0
depth = 2
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:Animal"
parent = "ex:Cat"
priority = 1.0
violation = 0
depth = 0
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:Animal"
parent = "ex:Organism"
priority = 1.0
violation = 0
depth = 0
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:NeuroRobot"
parent = "ex:Robot"
priority = 1.0
violation = 0
depth = 2
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:Organism"
parent = "owl:Thing"
priority = 1.0
violation = 0
depth = 1
repair_cost = 9.223372036854776e18

[[subClassOf]]
subject = "ex:Robot"
parent = "owl:Thing"
priority = 1.0
violation = 0
depth = 1
repair_cost = 9.223372036854776e18

[[disjointWith]]
left = "ex:Organism"
right = "ex:Robot"
priority = 1.0
violation = 0
depth = 1
repair_cost = 9.223372036854776e18

